#!/bin/bash

disown %%

if (( $# != 1 )); 
then
   	echo You must input an integer as the only argument
else
	if [[ $1 =~ ^-?[0-9]+$ ]]; 
	then
		for((i = 0; i < $1; i++)) do 
			if [[ `adb devices|grep emulator` != "" ]]; 
   			then
				length = 20
				i=$(($length-1))
				sleep $(($length*60))
				adb -e emu kill
			fi

			sleep 60
	
		done
	else
		echo You must input an integer as the only argument
	fi
fi
