#!/bin/bash

function terminatePreviousInstances()
{
	IFS='
' read -r -a array <<< `pgrep -f killdroid`

	echo Parsed
	
	for item in "${array[@]}"
	do
		if (( "$$" != "$item" ));
		then
			echo $item
		fi
	done

	echo Out
}

if (( $# != 1 && $# != 2 )); 
then
   	echo You must input must have either one or two integers as arguments.
else
	if [[ $1 =~ ^-?[0-9]+$ ]]; 
	then
		if (( $# == 2 ));
        	then
                	if [[ $2 =~ ^-?[0-9]+$ ]];
                	then
                        	length=$2
                	else
                        	length=20
                	fi
        	else
                	length=20
        	fi
		
		#terminatePreviousInstances
		
		pkill -f killdroid

		for((i = 0; i < $1; i++)) do 
			if [[ `adb devices|grep emulator` != "" ]]; 
   			then
				i=$(($length-1))
				sleep $(($length*60))
				adb -e emu kill
			fi

			sleep 60
	
		done
	else
		echo You must input must have either one or two integers as arguments.
	fi
fi
